# Generated by Django 3.1.6 on 2021-03-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='createCredentials',
        ),
    ]
