# Generated by Django 3.1.6 on 2021-03-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0002_auto_20210306_0558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createCredentials',
            new_name='Credential',
        ),
    ]
