# Generated by Django 3.1.6 on 2021-03-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0003_auto_20210306_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='betHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_lose', models.CharField(max_length=250)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='liveSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('team1', models.CharField(max_length=250)),
                ('team2', models.CharField(max_length=250)),
                ('dateTime', models.CharField(max_length=250)),
                ('live', models.CharField(max_length=250)),
                ('point1', models.CharField(max_length=250)),
                ('point2', models.CharField(max_length=250)),
                ('point3', models.CharField(max_length=250)),
                ('point4', models.CharField(max_length=250)),
                ('point5', models.CharField(max_length=250)),
                ('point6', models.CharField(max_length=250)),
                ('liveInfo', models.CharField(max_length=250)),
                ('score1', models.CharField(max_length=250)),
                ('score2', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='myBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('sport', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='BettingApp.livesport')),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('available', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.AddField(
            model_name='mybet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='BettingApp.userinfo'),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='myBet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='BettingApp.mybet'),
        ),
    ]
