# Generated by Django 3.1.6 on 2021-03-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0004_auto_20210308_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bethistory',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
