# Generated by Django 3.1.6 on 2021-03-08 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0005_auto_20210308_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bethistory',
            old_name='myBet',
            new_name='mybet',
        ),
        migrations.AddField(
            model_name='bethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 8, 6, 13, 49, 264321, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bethistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='livesport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 8, 6, 13, 54, 289028, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livesport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mybet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 8, 6, 13, 58, 431786, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
