# Generated by Django 3.1.6 on 2021-03-08 06:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0006_auto_20210308_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 8, 6, 15, 44, 872568, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
