# Generated by Django 3.1.6 on 2021-03-14 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0008_auto_20210308_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybet',
            old_name='balance',
            new_name='ticketNo',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='sport',
        ),
        migrations.AddField(
            model_name='mybet',
            name='Description',
            field=models.TextField(default='gaem details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybet',
            name='placed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mybet',
            name='user_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mybet',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BettingApp.userinfo'),
        ),
    ]
