# Generated by Django 3.1.6 on 2021-03-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0009_auto_20210315_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bethistory',
            old_name='balance',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='bethistory',
            name='mybet',
        ),
        migrations.RemoveField(
            model_name='bethistory',
            name='win_lose',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='Description',
        ),
        migrations.AddField(
            model_name='bethistory',
            name='game_point_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='matchDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='panelTitle',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='placed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='risk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='team1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='team2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='ticketNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='user_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='whomtobet',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='win_loss_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bethistory',
            name='win_loss_status',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mybet',
            name='game_point_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mybet',
            name='matchDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mybet',
            name='panelTitle',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mybet',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mybet',
            name='team1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mybet',
            name='team2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mybet',
            name='whomtobet',
            field=models.CharField(default='', max_length=260),
        ),
        migrations.AlterField(
            model_name='bethistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='BettingApp.userinfo'),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='dateTime',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='live',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='liveInfo',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point3',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point4',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point5',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='point6',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='score1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='score2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='sportCategory',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='team1',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='livesport',
            name='team2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='placed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='user_phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
