# Generated by Django 3.1.6 on 2021-03-21 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0010_auto_20210315_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='componentBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('e', models.IntegerField(default=0)),
                ('p', models.CharField(default='', max_length=50)),
                ('m', models.IntegerField(default=0)),
                ('k', models.IntegerField(default=0)),
                ('v', models.IntegerField(default=0)),
                ('sk', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='liveSport',
        ),
        migrations.RenameField(
            model_name='mybet',
            old_name='point',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='mybet',
            old_name='ticketNo',
            new_name='sizeEnabled',
        ),
        migrations.RenameField(
            model_name='mybet',
            old_name='win',
            new_name='userFreeBetId',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='game_point_details',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='matchDate',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='panelTitle',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='placed',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='user_phone',
        ),
        migrations.RemoveField(
            model_name='mybet',
            name='whomtobet',
        ),
        migrations.AddField(
            model_name='mybet',
            name='a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mybet',
            name='betType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='componentbet',
            name='myBets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BettingApp.mybet'),
        ),
    ]
