# Generated by Django 3.1.6 on 2021-03-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0012_mybet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentbet',
            old_name='myBets',
            new_name='myBet',
        ),
    ]
