# Generated by Django 3.1.6 on 2021-03-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0013_auto_20210321_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybet',
            name='classifier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mybet',
            name='eventId',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mybet',
            name='groupName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mybet',
            name='label',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mybet',
            name='line',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mybet',
            name='marketId',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mybet',
            name='marketName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mybet',
            name='oddsName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mybet',
            name='oddsVal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='accept',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='risk',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='sizeEnabled',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='userFreeBetId',
            field=models.FloatField(default=0),
        ),
    ]
