# Generated by Django 3.1.6 on 2021-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0015_mybet_towin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybet',
            name='placed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mybet',
            name='ticketno',
            field=models.IntegerField(default=0),
        ),
    ]
