# Generated by Django 3.1.6 on 2021-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0016_auto_20210327_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybet',
            name='teamname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mybet',
            name='eventId',
            field=models.IntegerField(default=0),
        ),
    ]
