# Generated by Django 3.1.7 on 2021-03-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0017_auto_20210327_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='accountLimit',
            field=models.IntegerField(default=300),
        ),
    ]
