# Generated by Django 3.1.6 on 2021-03-27 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BettingApp', '0018_userinfo_accountlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybet',
            name='placed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
